name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: linux
            binary-path: target/release/chisels_and_importers
          - os: windows-latest
            name: windows
            binary-path: target/release/chisels_and_importers.exe
      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.name }}
          path: ${{ matrix.binary-path }}
          if-no-files-found: error

  package:
    name: Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows]
      fail-fast: true
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-${{ matrix.platform }}
      - name: Create release directory
        run: |
          mkdir release
          cp chisels_and_importers* ./release/
          cp README.md ./release/
      - uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.platform }}
          path: ./release/*
          if-no-files-found: error

  release-github:
    name: Add build to GitHub release
    runs-on: ubuntu-latest
    needs: [package]
    permissions:
      contents: write
    strategy:
      matrix:
        platform: [linux, windows]
        include:
          - platform: linux
            archive-command: tar zcvf chisels_and_importers.tar.gz
            output-path: chisels_and_importers.tar.gz
          - platform: windows
            archive-command: zip -r chisels_and_importers.zip
            output-path: chisels_and_importers.zip
      fail-fast: true
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-${{ matrix.platform }}
          path: release
      - name: Creating archive
        run: |
          cd release
          ${{ matrix.archive-command }} *
          mv ${{ matrix.output-path }} ..
      - name: Attach packaged build to release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.output-path }}
